name: 'Terragrunt Binary Installer Action'
description: 'Install a specific version of the terragrunt binary.'
author: 'Peter Murray'

inputs:
  terragrunt_version:
    description: 'Terragrunt version to install'
    required: true

outputs:
  terragrunt_path:
    description: 'Path to the terragrunt binary'

branding:
  icon: cloud
  color: 'orange'

runs:
  using: 'node12'
  main: 'lib/index.js'
